a = str(input("Mening ismim: "))
b = str(input("Mening Familiyam: ")) 
c = int(input("Mening yoshim: "))
d = int(input("Mening telefon raqamim: "))
e = str(input("Mening elektron pochta manzilim: "))
print("Mening ismim: ", a)
print("Mening familiyam: ", b)
print("Mening yoshim ", c)
print("Mening telefon raqamim ", d)                                                                       
print("Mening elektron pochta manzilim ", e)